language: python
python:
    - 3.6
install:
    - pip install -r requirements.txt flake8 python-coveralls
script:
    - ./manage.py migrate
    - coverage run manage.py test
    - flake8 .
after_success:
    - coveralls
