language: python
python:
  - 3.6
install:
  - pip install pipenv
  - pipenv install --deploy --dev
script:
  - ./manage.py migrate
  - coverage run manage.py test
  - flake8 .
  - yapf -dr .
  - safety check
  - pip install 'git+https://github.com/nim65s/django-comptes.git#egg=comptes'
after_success:
  - coveralls
