[tool.poetry]
name = "comptes"
version = "2.0.1"
description = "Gestion des comptes"
authors = ["Guilhem Saurel <guilhem.saurel@laas.fr>"]
license = "BSD-2-CLause"

[tool.poetry.dependencies]
python = "^3.6.1"
ndh = "^3.10.4"
dmdm = "^1.4.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.0"
python-coveralls = "^2.9.3"
safety = "^1.10.3"
yapf = "^0.31.0"
mypy = "^0.812"
setuptools-scm = "^6.0.1"
pydocstyle = "^6.0.0"
pre-commit = "^2.11.1"
django-stubs = "^1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
