# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 17:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0012_cree_modifie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dette',
            name='creancier',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='creances',
                to=settings.AUTH_USER_MODEL,
                verbose_name='créancier'),
        ),
        migrations.AlterField(
            model_name='dette',
            name='cree',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé'),
        ),
        migrations.AlterField(
            model_name='dette',
            name='debiteurs',
            field=models.ManyToManyField(related_name='dettes', to=settings.AUTH_USER_MODEL, verbose_name='débiteurs'),
        ),
        migrations.AlterField(
            model_name='dette',
            name='modifie',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='debut',
            field=models.DateTimeField(verbose_name='début'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='credite',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='credits',
                to=settings.AUTH_USER_MODEL,
                verbose_name='crédité'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='crediteur',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='debits',
                to=settings.AUTH_USER_MODEL,
                verbose_name='créditeur'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='cree',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='modifie',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié'),
        ),
    ]
