# Generated by Django 2.0.1 on 2018-01-06 20:54

from django.db import migrations, models

import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0013_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='name',
            field=models.CharField(default='noname', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occasion',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
