# Generated by Django 2.0.1 on 2018-01-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0016_remove_occasion_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dette',
            name='cree',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dette',
            name='modifie',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='cree',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='modifie',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
