# Generated by Django 2.0.1 on 2018-01-06 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0018_auto_20180106_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='dette',
            name='moment',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remboursement',
            name='moment',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
