# Generated by Django 2.0.1 on 2018-01-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0020_auto_20180106_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dette',
            options={'ordering': ['-moment']},
        ),
        migrations.AlterModelOptions(
            name='remboursement',
            options={'ordering': ['-moment']},
        ),
        migrations.RemoveField(
            model_name='dette',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dette',
            name='time',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='remboursement',
            name='time',
        ),
    ]
